[package]
name = "example-bin"
version = "0.1.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]

[dependencies]
init = { path = "../init" }
example-lib = { path = "../example-lib" }

[build-dependencies]
init = { path = "../init" }
